#! cache needs to be cleaned everytime we change this file
services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false

  # register event
  OvanGmbh\ClassYear\EventListener\DocumentSave:
    tags:
      - name: event.listener
        identifier: 'afterDocumentSave'
        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent


  dashboard.widget.ovangmbh.classyear.dataProvider:
    class: 'OvanGmbh\ClassYear\Widgets\Provider\StudentsByLevelProvider'
    public: true

  # register dashboard widget 
  dashboard.widget.ovangmbh.classyear.studentsPerCouse:
    class: 'OvanGmbh\ClassYear\Widgets\MyDonut'
    arguments:
      $dataProvider: '@dashboard.widget.ovangmbh.classyear.dataProvider'
      $view: '@dashboard.views.widget'
      $options:
         refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'studentsPerCouse'
        groupNames: 'systemInfo'
        title: 'Students per course'
        description: 'Chart with the number of students per class'
        iconIdentifier: 'content-widget-chart-pie'
        height: 'medium'
  
  # register command
  OvanGmbh\ClassYear\Command\ListStudentsCommand:
    tags:
      - name: 'console.command'
        command: 'classyear:liststudents'
