base: 'https://highschool.ddev.site/'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
rootPageId: 1
routes: {  }

routeEnhancers:
  ListClassroomStudents:
    type: Extbase
    extension: ClassYear
    plugin: StudentList
    defaultController: 'Main::list'
    defaults:
      classroomUid: '-1'
    routes:
      - routePath: '/{classroom_name}/{classroomUid}'
        _controller: 'Main::list'
    aspects:
      classroomUid:
        type: PersistedPatternMapper
        tableName: 'tx_classyear_domain_model_classroom'
        routeFieldPattern: '^(?P<slug>.+)'
        routeFieldResult: "{slug}"
      # to translate /filter/ into different languages
      classroom_name:
        type: LocaleModifier
        default: 'classroom'
        localeMap:
          - locale: 'en_EN.*'
            value: 'classroom'
          - locale: 'es_ES.*'
            value: 'clase'