base: 'https://highschool.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
  -
    title: Spanish
    enabled: true
    languageId: 1
    base: /es/
    typo3Language: es
    locale: es_ES.UTF-8
    iso-639-1: es
    navigationTitle: Spanish
    hreflang: es-ES
    direction: ltr
    flag: es
    websiteTitle: ''
    fallbackType: strict
    fallbacks: ''
rootPageId: 1
routeEnhancers:
  ListClassroomStudents:
    type: Extbase
    extension: ClassYear
    plugin: StudentList
    defaultController: 'Main::list'
    defaults:
      classroomUid: '-1'
    routes:
      -
        routePath: '/{classroom_name}/{classroomUid}'
        _controller: 'Main::list'
    aspects:
      classroomUid:
        type: PersistedPatternMapper
        tableName: tx_classyear_domain_model_classroom
        routeFieldPattern: '^(?P<slug>.+)'
        routeFieldResult: '{slug}'
      classroom_name:
        type: LocaleModifier
        default: classroom
        localeMap:
          -
            locale: 'en_EN.*'
            value: classroom
          -
            locale: 'es_ES.*'
            value: clase
  JsonPlug:
    type: Extbase
    extension: ClassYear
    plugin: JsonPlugin
    routes:
      -
        routePath: /api/classes
        _controller: 'Json::listClassrooms'
      -
        routePath: '/api/classrooms/{classroomUid}'
        _controller: 'Json::showClassroom'
  PageTypeSuffix:
    type: PageType
    index: index
    map:
      rss.feed: 13
      .json: 26
websiteTitle: ''
